dotnet test --filter DisplayName~C000
dotnet test --filter DisplayName~M000
dotnet test --filter DisplayName~E001
dotnet test --filter DisplayName~E002
dotnet test --filter DisplayName~E003
dotnet test --filter DisplayName~E004
dotnet test --filter DisplayName~E005
dotnet test --filter DisplayName~E006
dotnet test --filter DisplayName~E007
dotnet test --filter DisplayName~E008
dotnet test --filter DisplayName~EX001
dotnet test --filter DisplayName~EX002
dotnet test --filter DisplayName~EX003
dotnet test --filter DisplayName~EX004
dotnet test --filter DisplayName~EX005